//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3.DAL
{
    using _4.Entities;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_Car_RentalEntities : DbContext
    {
        public DB_Car_RentalEntities()
            : base("name=DB_Car_RentalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Branch> Branches { get; set; }
        public DbSet<Car> Cars { get; set; }
        public DbSet<Cartyp> Cartyps { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<RolesType> RolesTypes { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
