//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public Car()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int CarID { get; set; }
        public int Mileage { get; set; }
        public string Picture { get; set; }
        public string IsRepaired { get; set; }
        public string IsAvailable { get; set; }
        public int C_License_number { get; set; }
        public int BranchID { get; set; }
        public bool IsActiv { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Cartyp Cartyp { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
    }
}
