//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cartyp
    {
        public Cartyp()
        {
            this.Cars = new HashSet<Car>();
        }
    
        public int TypeID { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public int Year_of_Manufacturer { get; set; }
        public string Transmission { get; set; }
        public int Daily_cost { get; set; }
        public int Day_late { get; set; }
        public bool IsActiv { get; set; }
    
        public virtual ICollection<Car> Cars { get; set; }
    }
}
