//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public int UserID { get; set; }
        public System.DateTime Taking_Date { get; set; }
        public System.DateTime Return_Date { get; set; }
        public System.DateTime Actual_return_Date { get; set; }
        public int License_number { get; set; }
        public bool IsActiv { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual User User { get; set; }
    }
}
