//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Orders = new HashSet<Order>();
            this.RolesTypes = new HashSet<RolesType>();
        }
    
        public int UserID { get; set; }
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public string User_name { get; set; }
        public System.DateTime Birth_Date { get; set; }
        public string Gender { get; set; }
        public string E_mail { get; set; }
        public string Password { get; set; }
        public string Picture { get; set; }
        public bool IsActiv { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<RolesType> RolesTypes { get; set; }
    }
}
